from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import csv
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from django.http import HttpResponse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from courses.models import Course  


# 👨‍🏫 TEACHER REPORT
@login_required
def teacher_report(request):

    courses = Course.objects.all()

    return render(request, 'report/teacher_report.html', {
        'courses': courses
    })


# 👨‍🎓 STUDENT REPORT
@login_required
def student_report(request):

    courses = Course.objects.all()

    return render(request, 'report/student_report.html', {
        'courses': courses
    })


# 📄 DOWNLOAD REPORTs
@login_required
def download_pdf_report(request):

    response = HttpResponse(content_type='application/pdf')

    response['Content-Disposition'] = 'attachment; filename="syllabus_report.pdf"'

    # PDF setup
    p = canvas.Canvas(response, pagesize=letter)

    width, height = letter

    # ================= TITLE =================
    p.setFont("Helvetica-Bold", 22)
    p.drawString(170, 760, "Syllabus Tracker Report")

    # ================= USER INFO =================
    p.setFont("Helvetica", 12)

    p.drawString(
        50,
        720,
        f"Generated Date: {datetime.now().strftime('%d-%m-%Y %I:%M %p')}"
    )

    p.drawString(
        50,
        700,
        f"User: {request.user.username}"
    )

    # ================= TABLE HEADER =================
    y = 650

    p.setFont("Helvetica-Bold", 13)

    p.drawString(50, y, "Course")
    p.drawString(250, y, "Completion")
    p.drawString(400, y, "Status")

    y -= 20

    # line
    p.line(50, y, 550, y)

    y -= 30

    # ================= COURSE DATA =================

    if request.user.groups.filter(name='Teacher').exists():
        courses = Course.objects.filter(teacher=request.user)
    else:
        courses = Course.objects.all()

    p.setFont("Helvetica", 12)

    for course in courses:

        completion = getattr(course, 'completion', 0)

        status = "On Track"

        if completion < 50:
            status = "Behind"

        p.drawString(50, y, str(course.course_name))
        p.drawString(250, y, f"{completion}%")
        p.drawString(400, y, status)

        y -= 30

        # next page
        if y < 100:
            p.showPage()
            y = 750

    # ================= FOOTER =================
    p.setFont("Helvetica-Oblique", 10)

    p.drawString(
        180,
        40,
        "Generated by Syllabus Tracker System"
    )

    # save
    p.save()

    return response