# Generated by Django 6.0.3 on 2026-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_id_alter_enrollment_id_alter_topic_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
